import mongoose from 'mongoose';
import { Product } from '../models/Product.ts';
import { Expense } from '../models/Expense.ts';
import { Sale } from '../models/Sale.ts';
import { Purchase } from '../models/Purchase.ts';
import { Customer } from '../models/Customer.ts';
import { Supplier } from '../models/Supplier.ts';

export async function seedDemoDataForUser(userId: mongoose.Types.ObjectId): Promise<void> {
  // Check if user already has data
  const existingProducts = await Product.countDocuments({ userId });
  if (existingProducts > 0) return;

  const now = new Date();
  const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);

  // 1. Create Customers
  const [c1, c2, c3, c4] = await Customer.create([
    {
      userId,
      name: 'Aayush Shrestha',
      phone: '+977 9841234567',
      email: 'aayush.shrestha@gmail.com',
      panNumber: '301298456',
      province: 'Bagmati Province',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      wardNo: '10',
      tole: 'New Baneshwor',
      address: 'New Baneshwor, Ward 10, Kathmandu',
      totalPurchases: 18400,
      transactionCount: 3,
      totalDue: 6000,
      lastPurchaseDate: daysAgo(2),
      notes: 'Frequent buyer for office items and handicraft gifts',
    },
    {
      userId,
      name: 'Sunita Gurung',
      phone: '+977 9803456789',
      email: 'sunita.g@outlook.com',
      province: 'Gandaki Province',
      district: 'Kaski',
      municipality: 'Pokhara Metropolitan City',
      wardNo: '6',
      tole: 'Lakeside',
      address: 'Lakeside, Ward 6, Pokhara',
      totalPurchases: 25200,
      transactionCount: 2,
      totalDue: 0,
      lastPurchaseDate: daysAgo(6),
      notes: 'Boutique hotel gift shop order',
    },
    {
      userId,
      name: 'Bikash Adhikari',
      phone: '+977 9812987654',
      email: 'bikash.adhikari@yahoo.com',
      province: 'Bagmati Province',
      district: 'Lalitpur',
      municipality: 'Lalitpur Metropolitan City',
      wardNo: '3',
      tole: 'Pulchowk',
      address: 'Pulchowk, Ward 3, Lalitpur',
      totalPurchases: 8400,
      transactionCount: 1,
      totalDue: 2400,
      lastPurchaseDate: daysAgo(10),
      notes: 'Partially paid via eSewa, remainder due',
    },
    {
      userId,
      name: 'Thamel Crafts & Cafe',
      phone: '+977 9851098765',
      email: 'contact@thamelcrafts.np',
      panNumber: '601987654',
      province: 'Bagmati Province',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      wardNo: '29',
      tole: 'Thamel',
      address: 'Chaksibari Marg, Thamel, Kathmandu',
      totalPurchases: 33600,
      transactionCount: 2,
      totalDue: 0,
      lastPurchaseDate: daysAgo(12),
      notes: 'Bulk retail partner',
    },
  ]);

  // 2. Create Suppliers
  const [s1, s2, s3] = await Supplier.create([
    {
      userId,
      name: 'Himalayan Organic Tea & Produce Co.',
      contactPerson: 'Rameshwor Koirala',
      phone: '+977 9851034567',
      email: 'orders@himalayantea.com.np',
      panNumber: '600123987',
      province: 'Koshi Province',
      district: 'Ilam',
      municipality: 'Ilam Municipality',
      address: 'Bhanu Chowk, Ilam',
      totalPurchases: 35000,
      purchaseCount: 2,
      totalDue: 8000,
      lastPurchaseDate: daysAgo(22),
      notes: 'Direct grower and tea processor in Ilam',
    },
    {
      userId,
      name: 'New Road Tech & Accessories Importers',
      contactPerson: 'Sanjay Shakya',
      phone: '+977 9841876543',
      email: 'newroad.tech@gmail.com',
      panNumber: '602345678',
      province: 'Bagmati Province',
      district: 'Kathmandu',
      municipality: 'Kathmandu Metropolitan City',
      address: 'Pako, New Road, Kathmandu',
      totalPurchases: 42500,
      purchaseCount: 2,
      totalDue: 12500,
      lastPurchaseDate: daysAgo(25),
      notes: 'Wholesale electronics and gadgets distributor',
    },
    {
      userId,
      name: 'Pashmina & Handicraft Weavers Society',
      contactPerson: 'Kamala Tuladhar',
      phone: '+977 9801239876',
      email: 'nepalpashmina@mail.com.np',
      panNumber: '302456789',
      province: 'Bagmati Province',
      district: 'Bhaktapur',
      municipality: 'Madhyapur Thimi',
      address: 'Sano Thimi, Bhaktapur',
      totalPurchases: 50000,
      purchaseCount: 1,
      totalDue: 0,
      lastPurchaseDate: daysAgo(28),
      notes: 'Authentic 100% cashmere and wool handloom supplier',
    },
  ]);

  // 3. Create Products
  const p1 = await Product.create({
    userId,
    name: 'Fine Cashmere Pashmina Shawl',
    sku: 'PAS-001',
    category: 'Clothing & Handloom',
    buyingPrice: 2500,
    sellingPrice: 4200,
    quantityPurchased: 20,
    quantitySold: 12,
    currentStock: 8,
    unit: 'Piece',
    minimumStock: 4,
    supplier: s3.name,
    purchaseDate: daysAgo(28),
    isVatApplicable: true,
    notes: 'Premium pure handwoven Nepali pashmina shawl with tassel finish',
  });

  const p2 = await Product.create({
    userId,
    name: 'Ilam First Flush Orthodox Black Tea (250g)',
    sku: 'TEA-102',
    category: 'Food & Organic',
    buyingPrice: 350,
    sellingPrice: 600,
    quantityPurchased: 50,
    quantitySold: 36,
    currentStock: 14,
    unit: 'Packet',
    minimumStock: 10,
    supplier: s1.name,
    purchaseDate: daysAgo(22),
    isVatApplicable: false,
    notes: 'Single estate high-altitude organic whole-leaf tea from Ilam',
  });

  const p3 = await Product.create({
    userId,
    name: 'Wireless Ergonomic Dual-Mode Mouse',
    sku: 'WEM-303',
    category: 'Electronics',
    buyingPrice: 850,
    sellingPrice: 1450,
    quantityPurchased: 30,
    quantitySold: 22,
    currentStock: 8,
    unit: 'Piece',
    minimumStock: 5,
    supplier: s2.name,
    purchaseDate: daysAgo(25),
    isVatApplicable: true,
    notes: 'Bluetooth + 2.4GHz rechargeable wireless mouse',
  });

  const p4 = await Product.create({
    userId,
    name: 'Mustang Organic Apple Juice (750ml)',
    sku: 'APL-404',
    category: 'Food & Organic',
    buyingPrice: 280,
    sellingPrice: 450,
    quantityPurchased: 40,
    quantitySold: 32,
    currentStock: 8,
    unit: 'Bottle',
    minimumStock: 10,
    supplier: s1.name,
    purchaseDate: daysAgo(18),
    isVatApplicable: false,
    notes: 'Cold-pressed natural apple cider from Marpha, Mustang',
  });

  const p5 = await Product.create({
    userId,
    name: 'Handcrafted Copper Water Bottle (1L)',
    sku: 'COP-505',
    category: 'Handicraft & Utensils',
    buyingPrice: 1100,
    sellingPrice: 1850,
    quantityPurchased: 25,
    quantitySold: 21,
    currentStock: 4,
    unit: 'Piece',
    minimumStock: 5,
    supplier: s3.name,
    purchaseDate: daysAgo(20),
    isVatApplicable: false,
    notes: 'Pure hammered copper bottle with leak-proof brass cap (Low Stock!)',
  });

  // 4. Create Purchases
  await Purchase.create([
    {
      userId,
      billNumber: 'BILL-80-019',
      productId: p1._id,
      productName: p1.name,
      supplierId: s3._id,
      supplier: s3.name,
      supplierPhone: s3.phone,
      supplierPan: s3.panNumber,
      quantity: 20,
      unit: 'Piece',
      purchasePrice: 2500,
      subtotal: 50000,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalPurchaseCost: 50000,
      purchaseDate: daysAgo(28),
      paymentStatus: 'Paid',
      paymentMethod: 'Bank Transfer',
      amountPaid: 50000,
      amountDue: 0,
      notes: 'Initial lot of winter pashmina scarves',
    },
    {
      userId,
      billNumber: 'INV-ILAM-341',
      productId: p2._id,
      productName: p2.name,
      supplierId: s1._id,
      supplier: s1.name,
      supplierPhone: s1.phone,
      supplierPan: s1.panNumber,
      quantity: 50,
      unit: 'Packet',
      purchasePrice: 350,
      subtotal: 17500,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalPurchaseCost: 17500,
      purchaseDate: daysAgo(22),
      paymentStatus: 'Partially Paid',
      paymentMethod: 'ConnectIPS',
      amountPaid: 9500,
      amountDue: 8000,
      notes: 'First flush tea consignment (रु 8,000 due to pay)',
    },
    {
      userId,
      billNumber: 'NR-TECH-502',
      productId: p3._id,
      productName: p3.name,
      supplierId: s2._id,
      supplier: s2.name,
      supplierPhone: s2.phone,
      supplierPan: s2.panNumber,
      quantity: 30,
      unit: 'Piece',
      purchasePrice: 850,
      subtotal: 25500,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalPurchaseCost: 25500,
      purchaseDate: daysAgo(25),
      paymentStatus: 'Partially Paid',
      paymentMethod: 'Bank Transfer',
      amountPaid: 13000,
      amountDue: 12500,
      notes: 'New Road batch (रु 12,500 due to pay)',
    },
    {
      userId,
      billNumber: 'MUSTANG-912',
      productId: p4._id,
      productName: p4.name,
      supplierId: s1._id,
      supplier: s1.name,
      supplierPhone: s1.phone,
      quantity: 40,
      unit: 'Bottle',
      purchasePrice: 280,
      subtotal: 11200,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalPurchaseCost: 11200,
      purchaseDate: daysAgo(18),
      paymentStatus: 'Paid',
      paymentMethod: 'Fonepay',
      amountPaid: 11200,
      amountDue: 0,
      notes: 'Cider bottles received in wooden crates',
    },
    {
      userId,
      billNumber: 'COP-THIMI-11',
      productId: p5._id,
      productName: p5.name,
      supplierId: s3._id,
      supplier: s3.name,
      supplierPhone: s3.phone,
      quantity: 25,
      unit: 'Piece',
      purchasePrice: 1100,
      subtotal: 27500,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalPurchaseCost: 27500,
      purchaseDate: daysAgo(20),
      paymentStatus: 'Paid',
      paymentMethod: 'eSewa',
      amountPaid: 27500,
      amountDue: 0,
      notes: 'Copper bottles consignment',
    },
  ]);

  // 5. Create Sales with Invoices
  await Sale.create([
    {
      userId,
      invoiceNumber: 'INV-2081-0001',
      productId: p1._id,
      productName: p1.name,
      customerId: c1._id,
      customerName: c1.name,
      customerPhone: c1.phone,
      customerPan: c1.panNumber,
      customerAddress: c1.address,
      quantity: 3,
      unit: 'Piece',
      sellingPrice: 4200,
      buyingPrice: 2500,
      discount: 200,
      subtotal: 12400,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalAmount: 12400,
      paymentMethod: 'Fonepay',
      paymentStatus: 'Paid',
      amountPaid: 12400,
      amountDue: 0,
      saleDate: daysAgo(15),
      notes: 'Baneshwor client gift purchase',
    },
    {
      userId,
      invoiceNumber: 'INV-2081-0002',
      productId: p1._id,
      productName: p1.name,
      customerId: c4._id,
      customerName: c4.name,
      customerPhone: c4.phone,
      customerPan: c4.panNumber,
      customerAddress: c4.address,
      quantity: 8,
      unit: 'Piece',
      sellingPrice: 4200,
      buyingPrice: 2500,
      discount: 0,
      subtotal: 33600,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalAmount: 33600,
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      amountPaid: 33600,
      amountDue: 0,
      saleDate: daysAgo(12),
      notes: 'Thamel tourist retail store order',
    },
    {
      userId,
      invoiceNumber: 'INV-2081-0003',
      productId: p2._id,
      productName: p2.name,
      customerId: c1._id,
      customerName: c1.name,
      customerPhone: c1.phone,
      quantity: 10,
      unit: 'Packet',
      sellingPrice: 600,
      buyingPrice: 350,
      discount: 0,
      subtotal: 6000,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalAmount: 6000,
      paymentMethod: 'Cash',
      paymentStatus: 'Due',
      amountPaid: 0,
      amountDue: 6000,
      saleDate: daysAgo(2),
      notes: 'Credit sale - promised settlement on Friday (रु 6,000 due)',
    },
    {
      userId,
      invoiceNumber: 'INV-2081-0004',
      productId: p2._id,
      productName: p2.name,
      customerId: c2._id,
      customerName: c2.name,
      customerPhone: c2.phone,
      quantity: 26,
      unit: 'Packet',
      sellingPrice: 600,
      buyingPrice: 350,
      discount: 400,
      subtotal: 15200,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalAmount: 15200,
      paymentMethod: 'eSewa',
      paymentStatus: 'Paid',
      amountPaid: 15200,
      amountDue: 0,
      saleDate: daysAgo(6),
      notes: 'Pokhara hotel guest breakfast hampers',
    },
    {
      userId,
      invoiceNumber: 'INV-2081-0005',
      productId: p3._id,
      productName: p3.name,
      customerId: c3._id,
      customerName: c3.name,
      customerPhone: c3.phone,
      quantity: 6,
      unit: 'Piece',
      sellingPrice: 1450,
      buyingPrice: 850,
      discount: 300,
      subtotal: 8400,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalAmount: 8400,
      paymentMethod: 'Khalti',
      paymentStatus: 'Partially Paid',
      amountPaid: 6000,
      amountDue: 2400,
      saleDate: daysAgo(10),
      notes: 'IT office staff order (रु 2,400 due to receive)',
    },
    {
      userId,
      invoiceNumber: 'INV-2081-0006',
      productId: p3._id,
      productName: p3.name,
      customerName: 'Counter Customer (Walk-in)',
      customerPhone: '+977 9801122334',
      quantity: 16,
      unit: 'Piece',
      sellingPrice: 1450,
      buyingPrice: 850,
      discount: 0,
      subtotal: 23200,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalAmount: 23200,
      paymentMethod: 'Fonepay',
      paymentStatus: 'Paid',
      amountPaid: 23200,
      amountDue: 0,
      saleDate: daysAgo(4),
      notes: 'Multiple retail sales at New Road shop counter',
    },
    {
      userId,
      invoiceNumber: 'INV-2081-0007',
      productId: p4._id,
      productName: p4.name,
      customerName: 'Siddhartha Cafe & Lounge',
      customerPhone: '+977 9841009988',
      quantity: 32,
      unit: 'Bottle',
      sellingPrice: 450,
      buyingPrice: 280,
      discount: 400,
      subtotal: 14000,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalAmount: 14000,
      paymentMethod: 'Bank Transfer',
      paymentStatus: 'Paid',
      amountPaid: 14000,
      amountDue: 0,
      saleDate: daysAgo(5),
      notes: 'Weekly fresh juice supply',
    },
    {
      userId,
      invoiceNumber: 'INV-2081-0008',
      productId: p5._id,
      productName: p5.name,
      customerId: c2._id,
      customerName: c2.name,
      customerPhone: c2.phone,
      quantity: 21,
      unit: 'Piece',
      sellingPrice: 1850,
      buyingPrice: 1100,
      discount: 850,
      subtotal: 38000,
      isVatApplicable: false,
      vatRate: 13,
      vatAmount: 0,
      totalAmount: 38000,
      paymentMethod: 'ConnectIPS',
      paymentStatus: 'Paid',
      amountPaid: 38000,
      amountDue: 0,
      saleDate: daysAgo(1),
      notes: 'Copper wellness bottles order',
    },
  ]);

  // 6. Create Nepal Business Expenses
  await Expense.create([
    {
      userId,
      name: 'Shop Rental (New Road Commercial Plaza)',
      amount: 25000,
      date: daysAgo(20),
      category: 'Rent',
      paymentMethod: 'Bank Transfer',
      isPersonal: false,
      vendor: 'Shrestha Commercial Properties',
      notes: 'Monthly retail premises rent',
    },
    {
      userId,
      name: 'Store Assistant Monthly Wages',
      amount: 18000,
      date: daysAgo(5),
      category: 'Salary / Wages',
      paymentMethod: 'Bank Transfer',
      isPersonal: false,
      notes: 'Monthly salary remuneration for store helper',
    },
    {
      userId,
      name: 'Nepal Electricity Authority (NEA) Commercial Bill',
      amount: 3500,
      date: daysAgo(11),
      category: 'Electricity',
      paymentMethod: 'eSewa',
      isPersonal: false,
      billNumber: 'NEA-KTM-8902',
      notes: 'Monthly power and lighting bill paid via eSewa',
    },
    {
      userId,
      name: 'WorldLink Fiber Internet Subscription',
      amount: 1800,
      date: daysAgo(14),
      category: 'Internet',
      paymentMethod: 'Fonepay',
      isPersonal: false,
      billNumber: 'WL-789012',
      notes: 'High speed fiber office connectivity',
    },
    {
      userId,
      name: 'Local Transport & Courier (Pathao & Express Delivery)',
      amount: 2400,
      date: daysAgo(8),
      category: 'Transportation',
      paymentMethod: 'Khalti',
      isPersonal: false,
      notes: 'Stock delivery and parcel courier charges',
    },
    {
      userId,
      name: 'Fonepay & eSewa Merchant Gateway Fees',
      amount: 450,
      date: daysAgo(3),
      category: 'Payment Gateway Charges',
      paymentMethod: 'Bank Transfer',
      isPersonal: false,
      notes: 'Transaction processing commission deductions',
    },
    {
      userId,
      name: 'Eco-friendly Packaging Bags & Shipping Boxes',
      amount: 1600,
      date: daysAgo(9),
      category: 'Packaging',
      paymentMethod: 'Cash',
      isPersonal: false,
      vendor: 'Bagmati Paper & Bags',
      notes: 'Kraft paper carrier bags with shop logo stamp',
    },
    {
      userId,
      name: 'Kathmandu Ward Business Registration Renewal',
      amount: 2500,
      date: daysAgo(25),
      category: 'Government Fees',
      paymentMethod: 'Cash',
      isPersonal: false,
      notes: 'Annual local government business fee',
    },
  ]);

  // 7. Create Nepal Personal Expenses (Isolated from business)
  await Expense.create([
    {
      userId,
      name: 'Family Grocery & Kitchen Supplies (Bhatbhateni)',
      amount: 7500,
      date: daysAgo(10),
      category: 'Food',
      paymentMethod: 'Fonepay',
      isPersonal: true,
      notes: 'Monthly household grocery shopping',
    },
    {
      userId,
      name: 'Children School Monthly Tuition Fee',
      amount: 5000,
      date: daysAgo(7),
      category: 'Education',
      paymentMethod: 'Bank Transfer',
      isPersonal: true,
      notes: 'Private academy monthly fee',
    },
    {
      userId,
      name: 'Family Health Checkup & Pharmacy Medicines',
      amount: 2200,
      date: daysAgo(13),
      category: 'Medical',
      paymentMethod: 'Cash',
      isPersonal: true,
      notes: 'Norvic clinic prescription medicines',
    },
    {
      userId,
      name: 'Personal Mobile Balance (NTC & Ncell)',
      amount: 1200,
      date: daysAgo(4),
      category: 'Mobile / Internet',
      paymentMethod: 'eSewa',
      isPersonal: true,
      notes: 'Family prepaid topups',
    },
  ]);
}
